services:
  - type: web
    name: tax-calculator
    env: ruby
    buildCommand: |
      bundle install
      yarn install --frozen-lockfile
      rails assets:precompile
    startCommand: bundle exec puma -C config/puma.rb
    postDeployCommand: |
      bundle exec rails db:create db:migrate
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tax-calculator-database
          property: connectionString
      - key: RAILS_MASTER_KEY
        fromSecret: rails_master_key
      - key: RAILS_ENV
        value: production

databases:
  - type: postgres
    name: tax-calculator-database
    plan: free
    version: 13
    envVars:
      - key: DB_HOST
        fromService:
          name: tax-calculator-database
          property: host
      - key: DB_PORT
        fromService:
          name: tax-calculator-database
          property: port
      - key: DB_USERNAME
        fromService:
          name: tax-calculator-database
          property: user
      - key: DB_PASSWORD
        fromService:
          name: tax-calculator-database
          property: password
      - key: DB_NAME
        fromService:
          name: tax-calculator-database
          property: name